{{- if .Values.jira.integration -}}
apiVersion: v2.edp.epam.com/v1
kind: JiraServer
metadata:
  name: {{.Values.jira.name}}
spec:
  apiUrl: {{.Values.jira.apiUrl}}
  rootUrl: {{.Values.jira.rootUrl}}
  credentialName: {{.Values.jira.credentialName}}
{{end}}
