# permissions for end users to view cdstagedeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cdstagedeploy-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: edp-codebase-operator
    app.kubernetes.io/part-of: edp-codebase-operator
    app.kubernetes.io/managed-by: kustomize
  name: cdstagedeploy-viewer-role
rules:
- apiGroups:
  - v2.edp.epam.com
  resources:
  - cdstagedeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - v2.edp.epam.com
  resources:
  - cdstagedeployments/status
  verbs:
  - get
