apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gitservers.v2.edp.epam.com
spec:
  group: v2.edp.epam.com
  names:
    kind: GitServer
    listKind: GitServerList
    plural: gitservers
    singular: gitserver
    shortNames:
      - gs
  scope: Namespaced
  version: v1alpha1