apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: codebases.edp.epam.com
spec:
  group: edp.epam.com
  names:
    kind: Codebase
    listKind: CodebaseList
    plural: codebases
    singular: codebase
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            buildTool:
              type: string
            database:
              properties:
                capacity:
                  type: string
                kind:
                  type: string
                storage:
                  type: string
                version:
                  type: string
              required:
              - kind
              - version
              - capacity
              - storage
              type: object
            framework:
              type: string
            lang:
              type: string
            repository:
              properties:
                url:
                  type: string
              required:
              - url
              type: object
            route:
              properties:
                path:
                  type: string
                site:
                  type: string
              required:
              - site
              - path
              type: object
            strategy:
              type: string
          required:
          - lang
          - framework
          - buildTool
          - strategy
          - repository
          - route
          - database
          type: object
        status:
          properties:
            available:
              type: boolean
            lastTimeUpdated:
              type: object
            status:
              type: string
          required:
          - available
          - lastTimeUpdated
          - status
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
