apiVersion: apps/v1
kind: Deployment
metadata:
  name: codebase-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: codebase-operator
  template:
    metadata:
      labels:
        name: codebase-operator
    spec:
      serviceAccountName: edp
      containers:
        - name: codebase-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: REPLACE_VALUE
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "codebase-operator"
