apiVersion: apps/v1
kind: Deployment
metadata:
  name: codebase-operator-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: codebase-operator-v2
  template:
    metadata:
      labels:
        name: codebase-operator-v2
    spec:
      securityContext:
        runAsUser: 999 
        runAsNonRoot: true
        runAsGroup: 999
        fsGroup: 999
      serviceAccountName: edp
      containers:
        - name: codebase-operator-v2
          # Replace this with the built image name
          image: REPLACE_IMAGE
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
          env:
            - name: WATCH_NAMESPACE
              value: REPLACE_VALUE
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "codebase-operator-v2"
