global:
  edpName: ""
  platform: "openshift"
  database:
    enabled: true
    port: 5432
    host:
    name: "edp-db"

name: codebase-operator
annotations: {}
nodeSelector: {}
tolerations: []
affinity: {}
image:
  name: epamedp/codebase-operator
  # if not defined then .Chart.AppVersion is used
  version:
envs:
  - name: RECONCILATION_PERIOD
    value: "360"  # The value should be typed in minutes
  # Maximum number of parallel reconciliation codebasebranches
  - name: CODEBASE_BRANCH_MAX_CONCURRENT_RECONCILES
    value: 3
imagePullPolicy: "IfNotPresent"

resources:
  limits:
    memory: 192Mi
  requests:
    cpu: 50m
    memory: 64Mi

jira:
  integration: false
  name: "jira"
  apiUrl: "https://jiraeu-api.example.com"
  rootUrl: "https://jiraeu.example.com"
  credentialName: "jira-user"
