global:
  edpName: ""
  platform: "openshift"
name: codebase-operator
database:
  required: false
  host: edp-install-wizard-db
  name: edp-install-wizard-db
  port: 5432
image:
  name: epamedp/codebase-operator
  version: v2.4.0

jira:
  integration: true
  name: "epam-jira"
  apiUrl: "https://jiraeu-api.epam.com"
  rootUrl: "https://jiraeu.epam.com"
  credentialName: "epam-jira-user"