global:
  edpName: ""
  platform: "openshift"
  database:
    enabled: true
    port: 5432
    host:
    name: "edp-db"

name: codebase-operator
image:
  name: epamedp/codebase-operator
  version: v2.4.0

resources:
  limits:
    memory: 192Mi
  requests:
    cpu: 50m
    memory: 64Mi

jira:
  integration: true
  name: "epam-jira"
  apiUrl: "https://jiraeu-api.epam.com"
  rootUrl: "https://jiraeu.epam.com"
  credentialName: "epam-jira-user"
