global:
  edpName: ""
  platform: "openshift"
  database:
    enabled: true
    port: 5432
    host:
    name: "edp-db"

name: codebase-operator
annotations: {}
nodeSelector: {}
tolerations: []
affinity: {}
image:
  name: epamedp/codebase-operator
  # if not defined then .Chart.AppVersion is used
  version:
imagePullPolicy: "IfNotPresent"

resources:
  limits:
    memory: 192Mi
  requests:
    cpu: 50m
    memory: 64Mi

jira:
  integration: true
  name: "epam-jira"
  apiUrl: "https://jiraeu-api.epam.com"
  rootUrl: "https://jiraeu.epam.com"
  credentialName: "epam-jira-user"
