name: codebase-operator
namespace: ""
platform: "openshift"
cdPipelineName: ""
cdPipelineStageName: ""
dnsWildcard: ""
database:
  required: false
  host: edp-install-wizard-db
  name: edp-install-wizard-db
  port: 5432
ingress:
  required: false
ingress:
  required: false
image:
  name: codebase-operator
  version: latest