{{- if eq .Values.global.platform "kubernetes" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "codebase-operator.labels" . | nindent 4 }}
  name: edp-{{ .Values.name }}-{{ .Values.global.edpName }}
rules:
- apiGroups:
    - '*'
  attributeRestrictions: null
  resources:
    - adminconsoles
    - adminconsoles/finalizers
    - adminconsoles/status
    - gitservers
    - gitservers/status
    - gitservers/finalizers
    - codebases
    - codebases/status
    - codebases/finalizers
    - codebasebranches
    - codebasebranches/status
    - codebasebranches/finalizers
    - codebaseimagestreams
    - codebaseimagestreams/status
    - codebaseimagestreams/finalizers
    - edpcomponents
    - edpcomponents/finalizers
    - edpcomponents/status
    - jenkins
    - jenkins/finalizers
    - jenkins/status
    - jenkinses
    - jenkinses/finalizers
    - jenkinses/status
    - jenkinsfolders
    - jenkinsfolders/finalizers
    - jenkinsfolders/status
    - jenkinsjobs
    - jenkinsjobs/finalizers
    - jenkinsjobs/status
    - jenkinsserviceaccounts
    - jenkinsserviceaccounts/finalizers
    - jenkinsserviceaccounts/status
    - jenkinsscripts
    - jenkinsscripts/finalizers
    - jenkinsscripts/status
    - jiraservers
    - jiraservers/finalizers
    - jiraservers/status
    - jirafixversions
    - jirafixversions/status
    - imagestreamtags
    - imagestreamtags/status
    - gittags
    - gittags/status
    - perfdatasourcejenkinses
    - perfdatasourcejenkinses/finalizers
    - perfdatasourcejenkinses/status
    - perfdatasourcesonars
    - perfdatasourcesonars/finalizers
    - perfdatasourcesonars/status
    - perfdatasourcegitlabs
    - perfdatasourcegitlabs/finalizers
    - perfdatasourcegitlabs/status
    - jiraissuemetadatas
    - jiraissuemetadatas/finalizers
    - jiraissuemetadatas/status
  verbs:
    - '*'
{{ end }}
