{{- if eq .Values.global.platform "openshift" -}}
apiVersion: authorization.openshift.io/v1
kind: Role
metadata:
  namespace: {{ .Values.global.edpName }}
  labels:
    {{- include "codebase-operator.labels" . | nindent 4 }}
  name: edp-{{ .Values.name }}
rules:
- apiGroups:
    - '*'
  resources:
    - adminconsoles
    - adminconsoles/finalizers
    - adminconsoles/status
    - gitservers
    - gitservers/status
    - gitservers/finalizers
    - codebases
    - codebases/status
    - codebases/finalizers
    - codebasebranches
    - codebasebranches/status
    - codebasebranches/finalizers
    - codebaseimagestreams
    - codebaseimagestreams/status
    - codebaseimagestreams/finalizers
    - configmaps
    - edpcomponents
    - edpcomponents/finalizers
    - edpcomponents/status
    - jenkins
    - jenkins/finalizers
    - jenkins/status
    - jenkinses
    - jenkinses/finalizers
    - jenkinses/status
    - jenkinsfolders
    - jenkinsfolders/finalizers
    - jenkinsfolders/status
    - jenkinsjobs
    - jenkinsjobs/finalizers
    - jenkinsjobs/status
    - jenkinsserviceaccounts
    - jenkinsserviceaccounts/finalizers
    - jenkinsserviceaccounts/status
    - jenkinsscripts
    - jenkinsscripts/finalizers
    - jenkinsscripts/status
    - jiraservers
    - jiraservers/finalizers
    - jiraservers/status
    - jirafixversions
    - jirafixversions/status
    - imagestreamtags
    - imagestreamtags/status
    - gittags
    - gittags/status
    - perfdatasourcejenkinses
    - perfdatasourcejenkinses/finalizers
    - perfdatasourcejenkinses/status
    - perfdatasourcesonars
    - perfdatasourcesonars/finalizers
    - perfdatasourcesonars/status
    - perfdatasourcegitlabs
    - perfdatasourcegitlabs/finalizers
    - perfdatasourcegitlabs/status
    - jiraissuemetadatas
    - jiraissuemetadatas/finalizers
    - jiraissuemetadatas/status
    - cdstagedeployments
    - cdstagedeployments/finalizers
    - cdstagedeployments/status
    - cdstagejenkinsdeployments
    - cdstagejenkinsdeployments/finalizers
    - cdstagejenkinsdeployments/status
    - stages
    - stages/finalizers
    - stages/status
  verbs:
    - '*'
- apiGroups:
    - coordination.k8s.io
  resources:
    - leases
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
- apiGroups:
    - networking.k8s.io
  resources:
    - ingresses
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - create
    - patch
{{ end }}
